export { MediaContentComponent } from './mediaContent'
export { HomeContentComponent } from './homeContent'
export { ArtistsContentComponent } from './artistsContent'
export { AboutContentComponent } from './aboutContent'
export { ContactContentComponent } from './contactContent'